### ISSUE TITLE
How to restore Move Line Up/Down?

### ISSUE THREAD

**Issue by blair55** [callum-ramage/ctrl-dir-scroll#22]
This overrides the default behaviour of ctrl+up/down which is to move the current line up/down. (Obviously, that's the purpose of the plugin)

My question is, is there a way to restore the move line behaviour so that it works under a different key combination?

**Comment by callum-ramage** [comment]
Add this to your keymap.json. You can find this file in the File menu.

I see the comment got removed from [keymaps/ctrl-dir-scroll.cson](https://github.com/callum-ramage/ctrl-dir-scroll/blob/master/keymaps/ctrl-dir-scroll.cson) in the last revision.

'body':
  'ctrl-shift-up': 'editor:move-line-up'
  'ctrl-shift-down': 'editor:move-line-down'

**Comment by callum-ramage** [comment]
Add this to your keymap.cson. You can find it under the File menu

'atom-workspace atom-text-editor':
  'ctrl-alt-up': 'editor:move-line-up'
  'ctrl-alt-down': 'editor:move-line-down'

**Comment by blair55** [comment]
Awesome, thank you.
