### ISSUE TITLE
Scrolling 1 line down in the top 3 lines of an editor where the content is smaller than the editor will cause the cursor to move to the 4th line

### ISSUE THREAD

**Issue by Hrafnahnef** [callum-ramage/ctrl-dir-scroll#26]
This issue affects only files opened in a editor, where the entirety of the file fits without scrolling inside the editor container and the "Scroll Past End" setting in "Editor" is turned off.

When the cursor is in the top 3 lines of the editor and the user initiates a scroll 1 line down (ctrl-down on linux), no scroll will happen but the cursor and the current line marking will still move as if a scroll took place, always moving the scroll to the 4th line of the file.

This only happens for the top of the file. The scroll-up event in the bottom of the file has no such bug.

**Comment by callum-ramage** [comment]
Thanks for the report. This should be fixed now. I changed the behaviour so that ctrl-dir-scroll is disabled when scroll past end is false and the document is smaller than the editor.
