### ISSUE TITLE
suddenly stopped working on Windows 10

### ISSUE THREAD

**Issue by garretwilson** [callum-ramage/ctrl-dir-scroll#28]
This was _such_ a nice feature. I've been using it every since it came out.

Suddenly today with Atom 1.19.0 ia32 on Windows 10 Pro 64-bit I noticed it isn't working anymore.

I did a `Ctrl+.` to see what the `Ctrl+Up` and `Ctrl+Down` keys were mapped to, and they are both still mapped to `ctrl-dir-scroll`, yet nothing happens. I've tested in `.js` and `.xml` files.

**Comment by weijarz** [comment]
Not working on atom 1.19 / Linux too.

**Comment by nathansobo** [comment]
This was caused by this package directly reading a field called `rowsPerPage` that moved to another object in Atom 1.19. The `getRowsPerPage` method continues to work. I've opened a PR to a add a getter shim for this field since this wasn't the only package to do this. JS should add property and method visibility declarations.

**Comment by garretwilson** [comment]
So you're saying they broke semantic versioning?

**Comment by garretwilson** [comment]
I just saw https://github.com/atom/atom/issues/15225#issuecomment-321643212. I was about to say that I read #15244 and and saw that `ctrl-dir-scroll` was using a non-public API. Naturally semantic versioning doesn't apply to private, unsupported APIs.

So `ctrl-dir-scroll` now uses the public API, and we'll get a fix published soon? If so, that's great news, thank you! I was about to throw Atom away, as I use this feature every day.

**Comment by garretwilson** [comment]
This seems to be fixed now!! Thank you very much for your quick response.

**Comment by nathansobo** [comment]
The fix hasn't been released yet though. Should go out with the next hotfix.

**Comment by garretwilson** [comment]
Um, but it seems to work now!

Do you mean that you added a workaround to the plugin, but that the shim hasn't made it into Atom yet for the other plugins?

**Comment by callum-ramage** [comment]
There was a pull request that fixed this so I merged it. (To explain why it started working)
94849266eb48909b78c54a840a394040ff193430
